/**
 * Convert the packages to a TypeDoc project, and derive the public API surface from it.
 *
 * ## Why a manifest exists at all
 *
 * The reference has to be generated from the declarations. That is what "the doc comments are the API
 * docs" was supposed to mean, and the numbers said otherwise. But a generated reference must not drift
 * from the source, and the two obvious ways to prevent that both fail here:
 *
 *   - **Commit the output and diff it.** 600+ markdown files, or ~10 MB of HTML; DESIGN §10 declines
 *     committing generated artifacts, and a reviewer cannot read a 600-file diff anyway.
 *   - **Generate it only on demand.** Then nothing notices when an export is added, renamed or dropped,
 *     which is exactly how the library came to publish internals as public API in the first place.
 *
 * So the gate diffs a *description* of the API instead of the API: module → kind → symbol names, sorted,
 * a few KB. `docs:check` regenerates it and fails on any difference, which makes an API change impossible
 * to land without someone looking at the reference.
 *
 * ## What the manifest does and does not claim
 *
 * It claims which symbols exist in which module, and what kind each is. It does not claim the prose is
 * good, and it cannot: a doc comment can be rewritten without the manifest changing. It catches the
 * structural half, the half that was actually broken.
 */

import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Application, ReflectionKind } from 'typedoc';
import { entryPoints } from './entry-points.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const REPO = path.resolve(HERE, '../..');
export const MANIFEST_PATH = path.join(REPO, 'docs', 'api-surface.json');
export const HTML_OUT = path.join(REPO, '.docs-api');

/**
 * TypeDoc's `ReflectionKind` reverse-maps numbers to names (`ReflectionKind[128] === 'Class'`), so the
 * manifest carries readable kinds rather than integers.
 *
 * The first version of this built a `Map` from `Object.entries`, which stringifies numeric keys: the map
 * held `"128"` while lookups passed `128`, so every kind silently became `Kind128`. The manifest looked
 * plausible, so it survived a passing `docs:check`; nothing compared kind *names* to anything.
 *
 * The fallback keeps an unrecognised kind visible in the manifest instead of dropping the symbol.
 */
const kindName = (kind) => ReflectionKind[kind] ?? `Kind${kind}`;

/** Convert every public entry point, with the internal declarations excluded. */
export async function convert() {
  const app = await Application.bootstrapWithPlugins({
    entryPoints,
    entryPointStrategy: 'resolve',
    out: HTML_OUT,
    name: 'magicgarden.js',
    readme: 'none',
    plugin: [path.join(HERE, 'module-tree.mjs')],
    // Declarations marked `@internal` are implementation details a caller cannot import; without this the
    // reference presents them as public surface.
    excludeInternal: true,
    logLevel: 'Warn',
    sourceLinkTemplate: 'https://github.com/QenuDev/MG.js/blob/main/{path}#L{line}',
    gitRevision: 'main',
  });

  const project = await app.convert();
  if (!project) throw new Error('typedoc produced no project, so the reference would be empty');
  return { app, project };
}

/** The public surface, as `{ modules: { 'pkg/module': { Class: [...], Interface: [...] } } }`. */
export function surfaceOf(project) {
  const modules = {};
  for (const module of [...(project.children ?? [])].sort((a, b) => a.name.localeCompare(b.name))) {
    const byKind = {};
    for (const child of module.children ?? []) {
      const kind = kindName(child.kind);
      const names = byKind[kind] ?? [];
      names.push(child.name);
      byKind[kind] = names;
    }
    const ordered = {};
    for (const kind of Object.keys(byKind).sort()) ordered[kind] = byKind[kind].sort();
    modules[module.name] = ordered;
  }
  return modules;
}

/** The manifest as it is written to disk, so `build` and `check` cannot disagree on formatting. */
export function serialise(modules) {
  return `${JSON.stringify(
    {
      $comment:
        'Generated by `npm run docs:build` from the TypeDoc project. `npm run docs:check` fails when this ' +
        'drifts from the source, so an API change cannot land unnoticed.',
      modules,
    },
    null,
    2,
  )}\n`;
}

/** A readable diff between two manifests, as lines. Empty when they agree. */
export function diffSurface(expected, actual) {
  const lines = [];
  const modules = [...new Set([...Object.keys(expected), ...Object.keys(actual)])].sort();
  for (const module of modules) {
    const before = expected[module];
    const after = actual[module];
    if (!before) {
      lines.push(`+ module ${module}`);
      continue;
    }
    if (!after) {
      lines.push(`- module ${module}`);
      continue;
    }
    for (const kind of [...new Set([...Object.keys(before), ...Object.keys(after)])].sort()) {
      const b = new Set(before[kind] ?? []);
      const a = new Set(after[kind] ?? []);
      for (const name of [...b].filter((n) => !a.has(n)).sort()) lines.push(`- ${module} ${kind} ${name}`);
      for (const name of [...a].filter((n) => !b.has(n)).sort()) lines.push(`+ ${module} ${kind} ${name}`);
    }
  }
  return lines;
}
